package telas;
/**
 *
 * @author Done
 */
import controle.Controle;
import javax.swing.table.DefaultTableModel;

public class TelaSimulacao extends javax.swing.JFrame {

    /**
     * Creates new form TabelaPrice
     */
    public TelaSimulacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFinanciamento = new javax.swing.JLabel();
        txtFinanciamento = new javax.swing.JTextField();
        lblPrazo = new javax.swing.JLabel();
        txtPrazo = new javax.swing.JTextField();
        lblJuros = new javax.swing.JLabel();
        txtJuros = new javax.swing.JTextField();
        botaoCALCULAREMPRESTIMO = new javax.swing.JButton();
        botaoCANCELAR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblSAC = new javax.swing.JLabel();
        lblPRICE = new javax.swing.JLabel();
        botaoPEGARSAC = new javax.swing.JButton();
        botaoPEGARPRICE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFinanciamento.setText("Financiamento:");

        lblPrazo.setText("Prazo:");

        lblJuros.setText("Juros:");

        botaoCALCULAREMPRESTIMO.setText("CALCULAR EMPRESTIMO");
        botaoCALCULAREMPRESTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCALCULAREMPRESTIMOActionPerformed(evt);
            }
        });

        botaoCANCELAR.setText("CANCELAR");
        botaoCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFinanciamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrazo)
                .addGap(41, 41, 41)
                .addComponent(txtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lblJuros)
                .addGap(38, 38, 38)
                .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCALCULAREMPRESTIMO)
                .addGap(180, 180, 180)
                .addComponent(botaoCANCELAR)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrazo)
                        .addComponent(txtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJuros)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCANCELAR)
                    .addComponent(botaoCALCULAREMPRESTIMO))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabelas"));
        jPanel2.setToolTipText("Calculos");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "SI", "JUROS", "AMORT", "PMT", "SF"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "SI", "JUROS", "AMORT", "PMT", "SF"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblSAC.setText("SAC");

        lblPRICE.setText("PRICE");

        botaoPEGARSAC.setText("PEGAR SAC");

        botaoPEGARPRICE.setText("PEGAR PRICE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lblSAC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPRICE)
                .addGap(218, 218, 218))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(botaoPEGARSAC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoPEGARPRICE)
                .addGap(177, 177, 177))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPRICE)
                    .addComponent(lblSAC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPEGARSAC)
                    .addComponent(botaoPEGARPRICE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCANCELARActionPerformed
        
        new TelaLogin().setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_botaoCANCELARActionPerformed

    private void botaoCALCULAREMPRESTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCALCULAREMPRESTIMOActionPerformed
     
        
        Emprestimo emprestimoSAC;
                
        Controle controlSAC = new Controle();
        
        emprestimoSAC = controlSAC.calculoSAC(
                Double.parseDouble(txtFinanciamento.getText()), 
                Double.parseDouble(txtJuros.getText()),
                Integer.parseInt(txtPrazo.getText()));
     
        DefaultTableModel modeloTableSAC = (DefaultTableModel) jTable1.getModel();
        
        while (modeloTableSAC.getRowCount() > 0){
            modeloTableSAC.removeRow(0);
        }
        
        
        int i = 0;
        for (Double item : emprestimoSAC.getSaldoInicial()) {
          
            modeloTableSAC.addRow(new Object[]{
            i + 1,
            item,
            emprestimoSAC.getJuros().get(i),
            emprestimoSAC.getAmortizacao().get(i),
            emprestimoSAC.getPmt().get(i),
            emprestimoSAC.getSaldoFinal().get(i),
            
            
            });
         i++;   
        }
        i = 0;
        
        
        
        Controle controlPRICE = new Controle();
        
        emprestimoSAC = controlPRICE.calculoPRICE(
                Double.parseDouble(txtFinanciamento.getText()), 
                Double.parseDouble(txtJuros.getText()),
                Integer.parseInt(txtPrazo.getText()));
     
        DefaultTableModel modeloTablePRICE = (DefaultTableModel) jTable2.getModel();
        
        while (modeloTablePRICE.getRowCount() > 0){
            modeloTablePRICE.removeRow(0);
        }
        
        
        int ii = 0;
        for (Double item : emprestimoSAC.getSaldoInicial()) {
          
            modeloTablePRICE.addRow(new Object[]{
            ii + 1,
            item,
            emprestimoSAC.getJuros().get(ii),
            emprestimoSAC.getAmortizacao().get(ii),
            emprestimoSAC.getPmt().get(ii),
            emprestimoSAC.getSaldoFinal().get(ii),
            
            
            });
         ii++;   
        }
        ii = 0;
        
        
    }//GEN-LAST:event_botaoCALCULAREMPRESTIMOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSimulacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCALCULAREMPRESTIMO;
    private javax.swing.JButton botaoCANCELAR;
    private javax.swing.JButton botaoPEGARPRICE;
    private javax.swing.JButton botaoPEGARSAC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblFinanciamento;
    private javax.swing.JLabel lblJuros;
    private javax.swing.JLabel lblPRICE;
    private javax.swing.JLabel lblPrazo;
    private javax.swing.JLabel lblSAC;
    private javax.swing.JTextField txtFinanciamento;
    private javax.swing.JTextField txtJuros;
    private javax.swing.JTextField txtPrazo;
    // End of variables declaration//GEN-END:variables
}
